### ISSUE TITLE
Additional dependencies

### ISSUE THREAD

**Issue by adamconkey** [uwgraphics/relaxed_ik#1]
When installing I also had to get `numba` and `ad` with `pip install numba` and `pip install ad`. Should these be listed as additional dependencies to install or are they maybe installed along with one of the other dependencies? These were needed at the collision viewer step.

**Comment by djrakita** [comment]
The current implementation actually doesn't use numba or ad, so I'll go in and remove those extra imports.  So, going forward, numba and ad won't be considered as dependencies.  Thanks for the heads up on that!
