### ISSUE TITLE
Does it support using .xacro format robot model file ?

### ISSUE THREAD

**Issue by ScottYang1982** [uwgraphics/relaxed_ik#18]
Does it support using .xacro format robot model file ? thank you!

**Comment by djrakita** [comment]
Hi, the urdf parser we use doesn't natively support xacro files, but converting from xacro to explicit urdf usually does the trick.  This page has the command I always use to do this conversion:
https://answers.ros.org/question/10401/how-to-convert-xacro-file-to-urdf-file/

If this doesn't work for you, just let me know!

**Comment by ScottYang1982** [comment]
@djrakita,
  Yes that works to convert urdf file, thank you!
