### ISSUE TITLE
How about enviroment collision avoidance other than self-collision function?

### ISSUE THREAD

**Issue by ScottYang1982** [uwgraphics/relaxed_ik#19]
How about enviroment collision avoidance other than self-collision function?

**Comment by djrakita** [comment]
I see you closed this issue, but I felt it was a really good question, so I thought I'd answer anyway.

Much of our ongoing research is actually working on effectively adding in environment collision avoidance to relaxedIK.  In particular, one of our recent papers (currently under review) adds in collision avoidance as one of the objective terms in the objective function, and it works surprisingly well for many applications.  We'll be open-sourcing this code very soon!
