### ISSUE TITLE
Confusion about the  Step 5a.

### ISSUE THREAD

**Issue by ScottYang1982** [uwgraphics/relaxed_ik#20]
Hi,
 About the Step 5a, what's exactly the purpose of selecting the "sample states"? That means the sample states create collision boundary ? Could you please explain it in detail, thank you!

**Comment by djrakita** [comment]
The “sample states” are a set of example states that are not in collision.  The neural network training is usually slightly more successful when these states are somewhat close to collision without actually being in collision as these states would inherently contain more information about the collision vs. non-collision boundary, but this is not a requirement.  The only actual requirement is that none of the sample states are in collision
