### ISSUE TITLE
the ur5.urdf

### ISSUE THREAD

**Issue by dydyddy** [uwgraphics/relaxed_ik#21]
Hi, Daniel Rakita, djrakita:
I'm a student pursuing a PhD degree.
I want to use the ur5.urdf to test the project, but in my computer, there is a error
[ERROR] [1606108638.445549825]: Could not load model 'package://ur_description/meshes/ur5/visual/upperarm.dae' ...
After I checking it, I think in the ur5.urdf, there is a label called 

geometry
mesh filename="package://ur_description/meshes/ur5/visual/upperarm.dae"/
/geometry

But I don't have the mesh source.
What can I do? I'm sorry the question seems naive to you.

**Comment by djrakita** [comment]
Hi, to fix this, you'll have to include ur_description as a ROS package in your catkin workspace.  If you don't know how to do this, many ROS tutorials will walk you through this.  Information on the ur_description package can be found here: http://wiki.ros.org/ur_description

Hope this helped!
