### ISSUE TITLE
Python3 migration?

### ISSUE THREAD

**Issue by cmower** [uwgraphics/relaxed_ik#23]
Hi,

Now that Python2 is officially deprecated, and ROS-Noetic targets Python3 exclusively, is there any plans to migrate or development migrating `relaxed_ik`?

**Comment by djrakita** [comment]
Hi Chris, yes, we are planning to move away from Python 2 going forward.  We have two plans for this: (1) our next release will get Python 2 completely out of the relaxedIK runtime; and (2) the release after that will get Python 2 out of the robot pre-processing/ compilation process as well.  Release #1 should be ready to go very soon (on the order of a week or two).  Release #2 will take a bit more time, maybe on the order of a few months.  I'll post some updates on the progress of these releases over the coming months!

**Comment by cmower** [comment]
Hi Daniel,
Thanks for this, re the pre-processing code, is this ROS dependant? Or can it be run using a python2 interpreter without calls to `rosrun`/`roslaunch`?

**Comment by djrakita** [comment]
Nothing about the underlying pre-processing code inherently requires ROS, but the way it's currently hooked up, ROS is a key part of the glue holding everything together.  In general, the goal going forward is to decouple and disentangle many of the underlying pieces of relaxedIK to allow for more flexibility and avoid these kind of common compatibility or deprecation issues.  And, even more broadly, we'll be aiming to take the software package from prototype research code to a more mature, well thought out software stack that will be easier to use and build on by people in the community
