### ISSUE TITLE
collision viewer fails to launch

### ISSUE THREAD

**Issue by robodreamer** [uwgraphics/relaxed_ik#4]
Hi, I was trying to follow the tutorial given in start_here.py with UR5 example. But I am stuck at Step 5b because of an error shown below. Would you be able to take a look and help me out? I really appreciate it and thanks for sharing the code. 

SUMMARY
========

PARAMETERS
 * /robot_state_publisher/publish_frequency: 50.0
 * /robot_state_publisher/tf_prefix: 
 * /rosdistro: kinetic
 * /rosversion: 1.12.14

NODES
  /
    robot_state_publisher (robot_state_publisher/robot_state_publisher)
    rviz (rviz/rviz)

ROS_MASTER_URI=http://localhost:11311
process[rviz-1]: started with pid [31991]
process[robot_state_publisher-2]: started with pid [31992]
Traceback (most recent call last):
  File "/home/andypark/catkin_ws/src/relaxed_ik/src/collision_viewer.py", line 44, in <module>
    joint_ordering,init_state=starting_config, collision_file=collision_file_name, pre_config=True)
  File "/home/andypark/catkin_ws/src/relaxed_ik/src/RelaxedIK/GROOVE_RelaxedIK/relaxedIK_vars.py", line 95, in __init__
    self.robot = Robot(self.arms, full_joint_lists,joint_order)
  File "/home/andypark/catkin_ws/src/relaxed_ik/src/RelaxedIK/Spacetime/robot.py", line 17, in __init__
    self.__initialize_bounds()
  File "/home/andypark/catkin_ws/src/relaxed_ik/src/RelaxedIK/Spacetime/robot.py", line 49, in __initialize_bounds
    idx = self.subchain_indices[i][j]
IndexError: list index out of range
[robot_state_publisher-2] killing on exit
[rviz-1] killing on exit
**[collision_viewer-1] process has died [pid 31940, exit code 1, cmd**
**/home/andypark/catkin_ws/src/relaxed_ik/src/collision_viewer.py __name:=collision_viewer**
**__log:=/home/andypark/.ros/log/9b6421f2-11ae-11e9-a8f2-18568023b643/collision_viewer-1.log].**
**log file: /home/andypark/.ros/log/9b6421f2-11ae-11e9-a8f2-18568023b643/collision_viewer-1.log**

**Comment by djrakita** [comment]
Absolutely, could you send along the start_here.py and urdf files you're using?  I'll try to replicate the error on my side using those files and fix anything that comes up.  Thanks

**Comment by robodreamer** [comment]
I tried using the code from your dev branch, and I was able to run some of the examples. Thanks!
