### ISSUE TITLE
I have a working python3.8 / ros noetic version

### ISSUE THREAD

**Issue by jstmn** [uwgraphics/relaxed_ik#40]
Hi there,

I have updated the code to run on Ubuntu 20 / ros-noetic / python3.8, the updated version is saved here: https://github.com/jstmn/relaxed_ik-ubuntu20/tree/dev-python38-noetic

There were a number of fixes I needed to make, including updating the python version to 3.8, fixing some julia bugs with Knet, and updating the ros joint_state_publisher, among others.

I'm happy to help add my version to this repo, let me know if that is something y'all (the maintainers) are interested in 

- Jeremy

**Comment by jstmn** [comment]
I see, thanks for the heads up. Do you know if stampede works with relaxed_ik_core?

**Comment by jstmn** [comment]
Also, may I suggest updating the readme for this repository so that others don't need to make the same fixes that I did?

**Comment by yepw** [comment]
Yes, I will change the readme to better link to relaxed_ik_core. 
 I don't think relaxed_ik_core works with stampede. For stampede, you can take a look at the [stampede](https://github.com/uwgraphics/stampede) repo and the [nylx](https://github.com/uwgraphics/lynx) repo.

**Comment by jstmn** [comment]
Sounds good. I looked through the nylx repository but didn't see any examples for doing pathwise-IK, does this functionality exist there yet?

**Comment by yepw** [comment]
I just realized that Stampede is only mentioned as future work in nylx' readme, so it's probably not implemented yet. I have never used nylx myself, sorry for the misleading message.

**Comment by jstmn** [comment]
Gotcha, no worries

**Comment by edward9503** [comment]
Hi @jstmn @yepw ,

thanks for the update on python 3.8. But I realized that some files are missing in the relax_ik_core repo, e.g., the collision_viewer.py, and some other files. Or maybe do I miss some info here in the readme?

Best
Shengzhi
