### ISSUE TITLE
Relaxed_IK moveit

### ISSUE THREAD

**Issue by UthiraS** [uwgraphics/relaxed_ik#41]
Hello,

I am trying to include relaxed IK into my move-it planner for ROS1 Noetic. I followed the instructions for setting up for Franka emika panda robot. I can see IK solvers like TrackIK have a plugin. Is it anything additional I need to do in order to include in a moveit ?

**Comment by yepw** [comment]
Hi @UthiraS, thank you for using our tool. Unfortunately, we haven't integrated it into MoveIt yet. I am sorry that I can't provide further help.
